"""empty message

Revision ID: 6921798dd5cf
Revises: 859b1654717e
Create Date: 2022-11-30 23:47:17.150847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6921798dd5cf'
down_revision = '859b1654717e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
